### PR TITLE
Support for cpe data and more lenient download location

### PR DESCRIPTION
**Pull request by goneall**
Implements code changes in issue #32

### CODE REVIEW

**Comment by goneall** [comment]
@flemminglau - if you could take a look at the changes and confirm I got the right source for the pull request

**Review by flemminglau — APPROVED** [review]
Yes, these are the changes I have done.

**Comment by goneall** [comment]
Thanks @flemminglau - I'll merge this in

**Comment by goneall** [comment]
Note: these are changes from this comment in issue #32: https://github.com/spdx/cdx2spdx/issues/32#issuecomment-1722947641

**Pull request merged**
